# Generated by Django 5.1.6 on 2025-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_posts_db_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts_db",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
