# Generated by Django 4.2 on 2025-03-27 06:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_posts_db_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts_db",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="default_slug_value",
                editable=False,
                populate_from="title",
            ),
            preserve_default=False,
        ),
    ]
