# Generated by Django 4.2 on 2025-03-27 06:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_posts_db_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts_db",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique=True
            ),
        ),
    ]
